[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
minkyc = "7nVLEY34rXaRTUjYHcbqeKZgSjxayCqeBPfCd1AtTAoW"

[programs.devnet]
minkyc = "DqULmbVsScRQGDtjUJEdptTjLkcPiH1rNCZRVUQc2hDL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/user2/.config/solana/minkyc-devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
